export const pfz=[
 {id:'PFZ-01',name:'Mumbai Offshore',lat:18.78,lng:72.72,confidence:92,distance:'42 km offshore',depth:'68–74 m',sst:27.4,chlorophyll:1.42,waves:1.2,wind:18,reason:{en:'Strong chlorophyll signal aligned with favourable SST.',hi:'मजबूत क्लोरोफिल संकेत अनुकूल SST के साथ मेल खाता है।',mr:'मजबूत क्लोरोफिल संकेत अनुकूल SST शी जुळतो.'}},
 {id:'PFZ-02',name:'Dahanu Shelf',lat:19.95,lng:72.72,confidence:86,distance:'58 km offshore',depth:'54–61 m',sst:26.9,chlorophyll:1.16,waves:1.0,wind:15,reason:{en:'Good ocean colour and temperature conditions.',hi:'अच्छे समुद्री रंग और तापमान की स्थिति।',mr:'चांगला समुद्री रंग आणि तापमानाची स्थिती.'}},
 {id:'PFZ-03',name:'Alibaug South',lat:18.48,lng:72.86,confidence:81,distance:'36 km offshore',depth:'48–55 m',sst:27.1,chlorophyll:1.08,waves:1.1,wind:16,reason:{en:'Moderate biological productivity with stable sea state.',hi:'स्थिर समुद्री स्थिति के साथ मध्यम जैविक उत्पादकता।',mr:'स्थिर समुद्रस्थितीसह मध्यम जैविक उत्पादकता.'}},
 {id:'PFZ-04',name:'Ratnagiri Shelf',lat:16.85,lng:72.55,confidence:88,distance:'49 km offshore',depth:'62–70 m',sst:26.7,chlorophyll:1.31,waves:1.3,wind:19,reason:{en:'High ocean-colour productivity with manageable sea state.',hi:'उच्च समुद्री उत्पादकता और नियंत्रित समुद्री स्थिति।',mr:'उच्च समुद्री उत्पादकता आणि नियंत्रित समुद्रस्थिती.'}},
 {id:'PFZ-05',name:'Goa Offshore',lat:15.05,lng:73.55,confidence:84,distance:'45 km offshore',depth:'57–65 m',sst:27.0,chlorophyll:1.22,waves:1.0,wind:14,reason:{en:'Balanced temperature and chlorophyll signals.',hi:'तापमान और क्लोरोफिल के संतुलित संकेत।',mr:'तापमान आणि क्लोरोफिलचे संतुलित संकेत.'}},
 {id:'PFZ-06',name:'Karwar Coast',lat:14.65,lng:73.55,confidence:79,distance:'31 km offshore',depth:'44–52 m',sst:27.2,chlorophyll:0.98,waves:0.9,wind:13,reason:{en:'Stable sea conditions with moderate productivity.',hi:'मध्यम उत्पादकता के साथ स्थिर समुद्री स्थिति।',mr:'मध्यम उत्पादकतेसह स्थिर समुद्रस्थिती.'}},
 {id:'PFZ-07',name:'Kochi Offshore',lat:9.72,lng:75.65,confidence:90,distance:'52 km offshore',depth:'66–73 m',sst:28.1,chlorophyll:1.36,waves:1.1,wind:17,reason:{en:'Strong productivity signal and suitable SST window.',hi:'मजबूत उत्पादकता संकेत और उपयुक्त SST अवधि।',mr:'मजबूत उत्पादकता संकेत आणि योग्य SST कालावधी.'}},
 {id:'PFZ-08',name:'Chennai East',lat:13.00,lng:80.65,confidence:76,distance:'39 km offshore',depth:'50–58 m',sst:28.0,chlorophyll:0.91,waves:1.4,wind:21,reason:{en:'Moderate PFZ signal; monitor wind before departure.',hi:'मध्यम PFZ संकेत; प्रस्थान से पहले हवा की निगरानी करें।',mr:'मध्यम PFZ संकेत; प्रस्थानापूर्वी वाऱ्याचे निरीक्षण करा.'}}
]
export const alerts=[
 {id:1,type:'Safety',severity:'Caution',title:{en:'Moderate sea state',hi:'मध्यम समुद्री स्थिति',mr:'मध्यम समुद्रस्थिती'},body:{en:'Waves around 1.2 m are expected along the Mumbai coast.',hi:'मुंबई तट के पास लगभग 1.2 मीटर लहरें अपेक्षित हैं।',mr:'मुंबई किनाऱ्याजवळ सुमारे 1.2 मीटर लाटा अपेक्षित आहेत.'}},
 {id:2,type:'Weather',severity:'Info',title:{en:'Favourable fishing window',hi:'अनुकूल मछली पकड़ने की अवधि',mr:'अनुकूल मासेमारी कालावधी'},body:{en:'Morning conditions are suitable for the selected PFZ.',hi:'चयनित PFZ के लिए सुबह की स्थिति उपयुक्त है।',mr:'निवडलेल्या PFZ साठी सकाळची परिस्थिती योग्य आहे.'}},
 {id:3,type:'Route',severity:'Caution',title:{en:'Caution corridor',hi:'सावधानी क्षेत्र',mr:'सावधगिरीचा मार्ग'},body:{en:'A higher-wind corridor is present south-east of the selected route.',hi:'चयनित मार्ग के दक्षिण-पूर्व में तेज हवा वाला क्षेत्र है।',mr:'निवडलेल्या मार्गाच्या आग्नेयेस जास्त वाऱ्याचा पट्टा आहे.'}}
]
